---
    - name: Установка UFW
      apt:
        update_cache: true
        name: ufw
        state: present

    - name: Отключение UFW (если уже запущен)
      ansible.builtin.ufw: 
        state: disabled

    - name: Установка политики по умолчанию
      command: |
        ufw default deny incoming
        ufw default allow outgoing

    - name: Разрешение порта SSH
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Включение UFW
      ansible.builtin.ufw: 
        state: enabled

    - name: Установка Snort
      apt:
        name: snort
        state: present

    - name: Настройка Snort для мониторинга трафика
      lineinfile:
        path: /etc/snort/snort.conf
        regexp: "^var HOME_NET"
        line: "var HOME_NET 192.168.1.0/24"

    - name: Запуск Snort в режиме демона
      service:
        name: snort
        state: started
        enabled: yes
